### ISSUE TITLE
Erori nesugestive

### ISSUE THREAD

**Issue by carmenacatrinei** [alexandra-udristoiu/MDS#15]
La HttpPut, functia de update arunca eroarea 403 (Forbidden), cand ar trebui sa returneze faptul ca obiectul respectiv nu exista in baza de date.
![unknown](https://user-images.githubusercontent.com/73901669/173376220-e3fed586-d31b-4fd1-9f61-aa884c810b04.png)

**Comment by MaraDascalu** [comment]
Codul de eroare a fost modificat sugestiv pentru fiecare functie de update a fiecarui controller.

![image](https://user-images.githubusercontent.com/74421271/173383791-e30ff96e-3317-4041-9572-086eb770bdeb.png)
