### ISSUE TITLE
Modificare pagina principala

### ISSUE THREAD

**Issue by MaraDascalu** [alexandra-udristoiu/MDS#9]
Modificari pentru pagina principala:
- butoanele, icon-ul user-ului si icon-ul meniului ar putea avea o alta culoare (de exemplu alb)
- intre numele utilizatorului si icon-ul sau ar putea exista un spatiu liber 

![287338157_685986509140473_2090795670412133427_n](https://user-images.githubusercontent.com/74421271/173226136-f3b3eb70-8abf-4255-8285-f8aa79b00540.png)

**Comment by LupascuMiruna** [comment]
Bugul a fost fixat conform ss-ului de mai jos
![image](https://user-images.githubusercontent.com/80571465/173227017-e817620b-895d-4a45-9d0b-283419d9fa69.png)
